### ISSUE TITLE
Drop stale metrics after deleting a check in Pingdom

### ISSUE THREAD

**Issue by danielfm** [jusbrasil/pingdom-exporter#1]
If we delete a check in Pingdom, the pingdom-exporter server will continue to report metrics for the dropped check. Currently, we need to restart pingdom-exporter for it to stop reporting metrics for the deleted check. 

Ideally, pingdom-exporter should detect dropped checks and stop reporting metrics for the deleted check.

**Comment by chxreyes** [comment]
I was reading the Prometheus docs on writing [collectors](https://prometheus.io/docs/instrumenting/writing_exporters/#collectors) and found this:

> When implementing the collector for your exporter, you should never use the usual direct instrumentation approach and then update the metrics on each scrape. ... Rather create new metrics each time. In Go this is done with MustNewConstMetric in your Collect() method. ... Secondly, if a label value disappears, it’ll still be exported.

This could be what is causing your problem. I have not been able to test it though.

**Comment by danielfm** [comment]
@CAReyes That must be it! I'll change the code to fix this when I get the chance.

Thanks for letting me know! :tada:

**Comment by danielfm** [comment]
Fixed in #2
